### ISSUE TITLE
UI doesn't update when new teams are added

### ISSUE THREAD

**Issue by hovo-hakobyan** [League-of-DAE-Legends/SquadForger#5]
In ```SquadVM``` The following function gets executed when ```Add``` button is pressed:
![image](https://github.com/League-of-DAE-Legends/SquadForger/assets/88614889/30857d48-d60c-4507-b38d-7eab0c558d41)
Which gets rid of the commas and creates new teams. The only issue is the UI doesn't show those changes.
The code inside ```SquadView```, responsible for showing it
![image](https://github.com/League-of-DAE-Legends/SquadForger/assets/88614889/b5d6161a-512f-44f4-a700-9bdb29373cc0)

**Comment by Wardergrip** [comment]
`ObservableContainer` from `System.Collections.ObjectModel` is a possible fix.

**Comment by hovo-hakobyan** [comment]
ObservableContainer did the trick
